### ISSUE TITLE
build procedure

### ISSUE THREAD

**Issue by souravg009** [ddrown/stm32-sump#3]
Hi,
I am in need of this logic analyser, but i am unable to build the hex file for stm32f103c8t6.
would you please describe build procedure and compiling in uVision5? I am getting errors like arm-none-eabi making some problems in compiling and caddr_t creating an error.
thanks.

**Comment by valoni** [comment]
or can provide hex file at least too

**Comment by ddrown** [comment]
I'm using arm-none-eabi-gcc 9.2.0 and newlib 3.1.0
I've published binaries here: https://github.com/ddrown/stm32-sump/releases/tag/v0.1
